/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ff0a7291-ef93-4e06-a57c-e2b71f9d2463",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_vXAV9h3AH",
    "aws_user_pools_web_client_id": "3en4nufq9ig417bu9k72eskp85",
    "oauth": {},
    "federationTarget": "COGNITO_IDENTITY_POOLS"
};


export default awsmobile;
